import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { viteSingleFile } from "vite-plugin-singlefile";

// The Rust dashboard serves exactly one route — `/` — via
// `include_str!("../../static/index.html")`. Building to a single inlined file
// keeps that true, so the UI ships with no changes to the server and no static
// asset routes to secure. It is also why routing is hash-based: the server
// would 404 on a real path.
export default defineConfig({
  // Stamped into the footer. `include_str!` bakes this file into the Rust
  // binary at compile time, so a rebuilt bundle does not reach a running
  // agent until cargo rebuilds too — this makes "am I looking at the new
  // build?" answerable from the page instead of by guessing.
  define: { __BUILD_ID__: JSON.stringify(new Date().toISOString().slice(0, 16).replace("T", " ")) },
  plugins: [
    react(),
    viteSingleFile(),
    {
      name: "generated-banner",
      transformIndexHtml(html: string) {
        return html.replace(
          /^<!doctype html>/i,
          "<!doctype html>\n<!-- GENERATED by polymarket-agent/ui — do not edit. Run `npm run build` in ui/. -->",
        );
      },
    },
  ],
  build: {
    outDir: "../static",
    emptyOutDir: false,
    cssCodeSplit: false,
    assetsInlineLimit: 100_000_000,
    chunkSizeWarningLimit: 4000,
  },
  server: {
    port: 5173,
    // `npm run dev` talks to a locally running agent.
    proxy: { "/api": "http://127.0.0.1:8080" },
  },
});
